/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scientific_calculator;
import java.awt.event.KeyEvent;
/**
 *
 * @author Lenovo
 */
public class scientific_cal extends javax.swing.JFrame {
double firstnum;
double secondnum;
double result;
String operations;
private Object math;
 String answer;
    /**
     * Creates new form scientific_cal
     */
    public scientific_cal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnclear1 = new javax.swing.JButton();
        btnfive1 = new javax.swing.JButton();
        btnhex1 = new javax.swing.JButton();
        btnseven1 = new javax.swing.JButton();
        btnroot1 = new javax.swing.JButton();
        btnsix1 = new javax.swing.JButton();
        btnback1 = new javax.swing.JButton();
        btncosh1 = new javax.swing.JButton();
        btnxy1 = new javax.swing.JButton();
        btnzero1 = new javax.swing.JButton();
        btnx1 = new javax.swing.JButton();
        btnlog1 = new javax.swing.JButton();
        btntanh1 = new javax.swing.JButton();
        btnround1 = new javax.swing.JButton();
        btnsubtr1 = new javax.swing.JButton();
        btncbr1 = new javax.swing.JButton();
        btnthree1 = new javax.swing.JButton();
        btntwo1 = new javax.swing.JButton();
        btnmulti1 = new javax.swing.JButton();
        btnone1 = new javax.swing.JButton();
        btnadd1 = new javax.swing.JButton();
        btnx5 = new javax.swing.JButton();
        btncos1 = new javax.swing.JButton();
        btntan1 = new javax.swing.JButton();
        btnsinh1 = new javax.swing.JButton();
        btndivide1 = new javax.swing.JButton();
        btnx4 = new javax.swing.JButton();
        btnplus1 = new javax.swing.JButton();
        textbox1 = new javax.swing.JTextField();
        btndot1 = new javax.swing.JButton();
        btnfour1 = new javax.swing.JButton();
        btnnine1 = new javax.swing.JButton();
        btnbinary1 = new javax.swing.JButton();
        btnequal1 = new javax.swing.JButton();
        btnsin1 = new javax.swing.JButton();
        btneight1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnx3 = new javax.swing.JButton();
        btnhex = new javax.swing.JButton();
        btnbinary = new javax.swing.JButton();
        textbox = new javax.swing.JTextField();
        btneight = new javax.swing.JButton();
        btnnine = new javax.swing.JButton();
        btnmulti = new javax.swing.JButton();
        btnseven = new javax.swing.JButton();
        btnfour = new javax.swing.JButton();
        btnfive = new javax.swing.JButton();
        btnsix = new javax.swing.JButton();
        btnsubtr = new javax.swing.JButton();
        btnone = new javax.swing.JButton();
        btntwo = new javax.swing.JButton();
        btnthree = new javax.swing.JButton();
        btndivide = new javax.swing.JButton();
        btnzero = new javax.swing.JButton();
        btndot = new javax.swing.JButton();
        btnplus = new javax.swing.JButton();
        btnequal = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnroot = new javax.swing.JButton();
        btnadd = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnsin = new javax.swing.JButton();
        btnsinh = new javax.swing.JButton();
        btnlog = new javax.swing.JButton();
        btncos = new javax.swing.JButton();
        btncosh = new javax.swing.JButton();
        btnx = new javax.swing.JButton();
        btnxy = new javax.swing.JButton();
        btntanh = new javax.swing.JButton();
        btntan = new javax.swing.JButton();
        btnx2 = new javax.swing.JButton();
        btnround = new javax.swing.JButton();
        btncbr = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        btnclear1.setBackground(new java.awt.Color(102, 102, 102));
        btnclear1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnclear1.setForeground(new java.awt.Color(255, 255, 255));
        btnclear1.setText("C");
        btnclear1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclear1ActionPerformed(evt);
            }
        });

        btnfive1.setBackground(new java.awt.Color(102, 102, 102));
        btnfive1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnfive1.setForeground(new java.awt.Color(255, 255, 255));
        btnfive1.setText("5");
        btnfive1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnfive1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfive1ActionPerformed(evt);
            }
        });

        btnhex1.setBackground(new java.awt.Color(102, 102, 102));
        btnhex1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnhex1.setForeground(new java.awt.Color(255, 255, 255));
        btnhex1.setText("Hex");
        btnhex1.setActionCommand("");
        btnhex1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnhex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhex1ActionPerformed(evt);
            }
        });

        btnseven1.setBackground(new java.awt.Color(102, 102, 102));
        btnseven1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnseven1.setForeground(new java.awt.Color(255, 255, 255));
        btnseven1.setText("7");
        btnseven1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnseven1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseven1ActionPerformed(evt);
            }
        });

        btnroot1.setBackground(new java.awt.Color(102, 102, 102));
        btnroot1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnroot1.setForeground(new java.awt.Color(255, 255, 255));
        btnroot1.setText("√");
        btnroot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnroot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroot1ActionPerformed(evt);
            }
        });

        btnsix1.setBackground(new java.awt.Color(102, 102, 102));
        btnsix1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnsix1.setForeground(new java.awt.Color(255, 255, 255));
        btnsix1.setText("6");
        btnsix1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnsix1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsix1ActionPerformed(evt);
            }
        });

        btnback1.setBackground(new java.awt.Color(102, 102, 102));
        btnback1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnback1.setForeground(new java.awt.Color(255, 255, 255));
        btnback1.setText("B");
        btnback1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnback1ActionPerformed(evt);
            }
        });

        btncosh1.setBackground(new java.awt.Color(102, 102, 102));
        btncosh1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btncosh1.setForeground(new java.awt.Color(255, 255, 255));
        btncosh1.setText("Cosh");
        btncosh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btncosh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosh1ActionPerformed(evt);
            }
        });

        btnxy1.setBackground(new java.awt.Color(102, 102, 102));
        btnxy1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnxy1.setForeground(new java.awt.Color(255, 255, 255));
        btnxy1.setText("X^Y");
        btnxy1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnxy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxy1ActionPerformed(evt);
            }
        });

        btnzero1.setBackground(new java.awt.Color(102, 102, 102));
        btnzero1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnzero1.setForeground(new java.awt.Color(255, 255, 255));
        btnzero1.setText("0");
        btnzero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnzero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzero1ActionPerformed(evt);
            }
        });

        btnx1.setBackground(new java.awt.Color(102, 102, 102));
        btnx1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnx1.setForeground(new java.awt.Color(255, 255, 255));
        btnx1.setText("Pi");
        btnx1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx1ActionPerformed(evt);
            }
        });

        btnlog1.setBackground(new java.awt.Color(102, 102, 102));
        btnlog1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnlog1.setForeground(new java.awt.Color(255, 255, 255));
        btnlog1.setText("Log");
        btnlog1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnlog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlog1ActionPerformed(evt);
            }
        });

        btntanh1.setBackground(new java.awt.Color(102, 102, 102));
        btntanh1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btntanh1.setForeground(new java.awt.Color(255, 255, 255));
        btntanh1.setText("Tanh");
        btntanh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btntanh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanh1ActionPerformed(evt);
            }
        });

        btnround1.setBackground(new java.awt.Color(102, 102, 102));
        btnround1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnround1.setForeground(new java.awt.Color(255, 255, 255));
        btnround1.setText("Run");
        btnround1.setActionCommand("");
        btnround1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnround1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnround1ActionPerformed(evt);
            }
        });

        btnsubtr1.setBackground(new java.awt.Color(102, 102, 102));
        btnsubtr1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsubtr1.setForeground(new java.awt.Color(255, 255, 255));
        btnsubtr1.setText("-");
        btnsubtr1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnsubtr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubtr1ActionPerformed(evt);
            }
        });

        btncbr1.setBackground(new java.awt.Color(102, 102, 102));
        btncbr1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btncbr1.setForeground(new java.awt.Color(255, 255, 255));
        btncbr1.setText("Cbr");
        btncbr1.setActionCommand("");
        btncbr1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btncbr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncbr1ActionPerformed(evt);
            }
        });

        btnthree1.setBackground(new java.awt.Color(102, 102, 102));
        btnthree1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnthree1.setForeground(new java.awt.Color(255, 255, 255));
        btnthree1.setText("3");
        btnthree1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnthree1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthree1ActionPerformed(evt);
            }
        });

        btntwo1.setBackground(new java.awt.Color(102, 102, 102));
        btntwo1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btntwo1.setForeground(new java.awt.Color(255, 255, 255));
        btntwo1.setText("2");
        btntwo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btntwo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntwo1ActionPerformed(evt);
            }
        });

        btnmulti1.setBackground(new java.awt.Color(102, 102, 102));
        btnmulti1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnmulti1.setForeground(new java.awt.Color(255, 255, 255));
        btnmulti1.setText("*");
        btnmulti1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnmulti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmulti1ActionPerformed(evt);
            }
        });

        btnone1.setBackground(new java.awt.Color(102, 102, 102));
        btnone1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnone1.setForeground(new java.awt.Color(255, 255, 255));
        btnone1.setText("1");
        btnone1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnone1ActionPerformed(evt);
            }
        });

        btnadd1.setBackground(new java.awt.Color(102, 102, 102));
        btnadd1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnadd1.setForeground(new java.awt.Color(255, 255, 255));
        btnadd1.setText("+");
        btnadd1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        btnx5.setBackground(new java.awt.Color(102, 102, 102));
        btnx5.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnx5.setForeground(new java.awt.Color(255, 255, 255));
        btnx5.setText("X^2");
        btnx5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx5ActionPerformed(evt);
            }
        });

        btncos1.setBackground(new java.awt.Color(102, 102, 102));
        btncos1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btncos1.setForeground(new java.awt.Color(255, 255, 255));
        btncos1.setText("Cos");
        btncos1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btncos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncos1ActionPerformed(evt);
            }
        });

        btntan1.setBackground(new java.awt.Color(102, 102, 102));
        btntan1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btntan1.setForeground(new java.awt.Color(255, 255, 255));
        btntan1.setText("Tan");
        btntan1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btntan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntan1ActionPerformed(evt);
            }
        });

        btnsinh1.setBackground(new java.awt.Color(102, 102, 102));
        btnsinh1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnsinh1.setForeground(new java.awt.Color(255, 255, 255));
        btnsinh1.setText("Sinh");
        btnsinh1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnsinh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinh1ActionPerformed(evt);
            }
        });

        btndivide1.setBackground(new java.awt.Color(102, 102, 102));
        btndivide1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btndivide1.setForeground(new java.awt.Color(255, 255, 255));
        btndivide1.setText("/");
        btndivide1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btndivide1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivide1ActionPerformed(evt);
            }
        });

        btnx4.setBackground(new java.awt.Color(102, 102, 102));
        btnx4.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnx4.setForeground(new java.awt.Color(255, 255, 255));
        btnx4.setText("X^3");
        btnx4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx4ActionPerformed(evt);
            }
        });

        btnplus1.setBackground(new java.awt.Color(102, 102, 102));
        btnplus1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnplus1.setForeground(new java.awt.Color(255, 255, 255));
        btnplus1.setText("±");
        btnplus1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnplus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplus1ActionPerformed(evt);
            }
        });

        textbox1.setFont(new java.awt.Font("Swis721 Lt BT", 1, 18)); // NOI18N
        textbox1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textbox1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));
        textbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox1ActionPerformed(evt);
            }
        });
        textbox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textbox1KeyTyped(evt);
            }
        });

        btndot1.setBackground(new java.awt.Color(102, 102, 102));
        btndot1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btndot1.setForeground(new java.awt.Color(255, 255, 255));
        btndot1.setText(".");
        btndot1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btndot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndot1ActionPerformed(evt);
            }
        });

        btnfour1.setBackground(new java.awt.Color(102, 102, 102));
        btnfour1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnfour1.setForeground(new java.awt.Color(255, 255, 255));
        btnfour1.setText("4");
        btnfour1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnfour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfour1ActionPerformed(evt);
            }
        });

        btnnine1.setBackground(new java.awt.Color(102, 102, 102));
        btnnine1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnnine1.setForeground(new java.awt.Color(255, 255, 255));
        btnnine1.setText("9");
        btnnine1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnnine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnine1ActionPerformed(evt);
            }
        });

        btnbinary1.setBackground(new java.awt.Color(102, 102, 102));
        btnbinary1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnbinary1.setForeground(new java.awt.Color(255, 255, 255));
        btnbinary1.setText("Bry");
        btnbinary1.setActionCommand("");
        btnbinary1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnbinary1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinary1ActionPerformed(evt);
            }
        });

        btnequal1.setBackground(new java.awt.Color(102, 102, 102));
        btnequal1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnequal1.setForeground(new java.awt.Color(255, 255, 255));
        btnequal1.setText("=");
        btnequal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnequal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequal1ActionPerformed(evt);
            }
        });

        btnsin1.setBackground(new java.awt.Color(102, 102, 102));
        btnsin1.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        btnsin1.setForeground(new java.awt.Color(255, 255, 255));
        btnsin1.setText("Sin");
        btnsin1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnsin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsin1ActionPerformed(evt);
            }
        });

        btneight1.setBackground(new java.awt.Color(102, 102, 102));
        btneight1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btneight1.setForeground(new java.awt.Color(255, 255, 255));
        btneight1.setText("8");
        btneight1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btneight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneight1ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnx3.setBackground(new java.awt.Color(102, 102, 102));
        btnx3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnx3.setText("X^3");
        btnx3.setBorder(null);
        btnx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx3ActionPerformed(evt);
            }
        });

        btnhex.setBackground(new java.awt.Color(102, 102, 102));
        btnhex.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnhex.setText("Hex");
        btnhex.setActionCommand("");
        btnhex.setBorder(null);
        btnhex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhexActionPerformed(evt);
            }
        });

        btnbinary.setBackground(new java.awt.Color(102, 102, 102));
        btnbinary.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnbinary.setText("Bry");
        btnbinary.setActionCommand("");
        btnbinary.setBorder(null);
        btnbinary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbinaryActionPerformed(evt);
            }
        });

        textbox.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        textbox.setForeground(new java.awt.Color(51, 51, 51));
        textbox.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        textbox.setBorder(null);
        textbox.setCaretColor(new java.awt.Color(255, 255, 255));
        textbox.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        textbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textboxActionPerformed(evt);
            }
        });
        textbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textboxKeyTyped(evt);
            }
        });

        btneight.setBackground(new java.awt.Color(102, 102, 102));
        btneight.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btneight.setText("8");
        btneight.setBorder(null);
        btneight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneightActionPerformed(evt);
            }
        });

        btnnine.setBackground(new java.awt.Color(102, 102, 102));
        btnnine.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnnine.setText("9");
        btnnine.setBorder(null);
        btnnine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnineActionPerformed(evt);
            }
        });

        btnmulti.setBackground(new java.awt.Color(102, 102, 102));
        btnmulti.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnmulti.setText("*");
        btnmulti.setBorder(null);
        btnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiActionPerformed(evt);
            }
        });

        btnseven.setBackground(new java.awt.Color(102, 102, 102));
        btnseven.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnseven.setText("7");
        btnseven.setBorder(null);
        btnseven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsevenActionPerformed(evt);
            }
        });

        btnfour.setBackground(new java.awt.Color(102, 102, 102));
        btnfour.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnfour.setText("4");
        btnfour.setBorder(null);
        btnfour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfourActionPerformed(evt);
            }
        });

        btnfive.setBackground(new java.awt.Color(102, 102, 102));
        btnfive.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnfive.setText("5");
        btnfive.setBorder(null);
        btnfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfiveActionPerformed(evt);
            }
        });

        btnsix.setBackground(new java.awt.Color(102, 102, 102));
        btnsix.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnsix.setText("6");
        btnsix.setBorder(null);
        btnsix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsixActionPerformed(evt);
            }
        });

        btnsubtr.setBackground(new java.awt.Color(102, 102, 102));
        btnsubtr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsubtr.setText("-");
        btnsubtr.setBorder(null);
        btnsubtr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubtrActionPerformed(evt);
            }
        });

        btnone.setBackground(new java.awt.Color(102, 102, 102));
        btnone.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnone.setText("1");
        btnone.setBorder(null);
        btnone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoneActionPerformed(evt);
            }
        });

        btntwo.setBackground(new java.awt.Color(102, 102, 102));
        btntwo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btntwo.setText("2");
        btntwo.setBorder(null);
        btntwo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntwoActionPerformed(evt);
            }
        });

        btnthree.setBackground(new java.awt.Color(102, 102, 102));
        btnthree.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnthree.setText("3");
        btnthree.setBorder(null);
        btnthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthreeActionPerformed(evt);
            }
        });

        btndivide.setBackground(new java.awt.Color(102, 102, 102));
        btndivide.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btndivide.setText("/");
        btndivide.setBorder(null);
        btndivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndivideActionPerformed(evt);
            }
        });

        btnzero.setBackground(new java.awt.Color(102, 102, 102));
        btnzero.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnzero.setText("0");
        btnzero.setBorder(null);
        btnzero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzeroActionPerformed(evt);
            }
        });

        btndot.setBackground(new java.awt.Color(102, 102, 102));
        btndot.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btndot.setText(".");
        btndot.setBorder(null);
        btndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndotActionPerformed(evt);
            }
        });

        btnplus.setBackground(new java.awt.Color(102, 102, 102));
        btnplus.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnplus.setText("±");
        btnplus.setBorder(null);
        btnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnplusActionPerformed(evt);
            }
        });

        btnequal.setBackground(new java.awt.Color(102, 102, 102));
        btnequal.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnequal.setText("=");
        btnequal.setBorder(null);
        btnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnequalActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(102, 102, 102));
        btnclear.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnclear.setText("C");
        btnclear.setBorder(null);
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        btnroot.setBackground(new java.awt.Color(102, 102, 102));
        btnroot.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnroot.setText("√");
        btnroot.setBorder(null);
        btnroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrootActionPerformed(evt);
            }
        });

        btnadd.setBackground(new java.awt.Color(102, 102, 102));
        btnadd.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnadd.setText("+");
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(102, 102, 102));
        btnback.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnback.setText("B");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        btnsin.setBackground(new java.awt.Color(102, 102, 102));
        btnsin.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnsin.setText("Sin");
        btnsin.setBorder(null);
        btnsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinActionPerformed(evt);
            }
        });

        btnsinh.setBackground(new java.awt.Color(102, 102, 102));
        btnsinh.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnsinh.setText("Sinh");
        btnsinh.setBorder(null);
        btnsinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsinhActionPerformed(evt);
            }
        });

        btnlog.setBackground(new java.awt.Color(102, 102, 102));
        btnlog.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnlog.setText("Log");
        btnlog.setBorder(null);
        btnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogActionPerformed(evt);
            }
        });

        btncos.setBackground(new java.awt.Color(102, 102, 102));
        btncos.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btncos.setText("Cos");
        btncos.setBorder(null);
        btncos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncosActionPerformed(evt);
            }
        });

        btncosh.setBackground(new java.awt.Color(102, 102, 102));
        btncosh.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btncosh.setText("Cosh");
        btncosh.setBorder(null);
        btncosh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncoshActionPerformed(evt);
            }
        });

        btnx.setBackground(new java.awt.Color(102, 102, 102));
        btnx.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnx.setText("Pi");
        btnx.setBorder(null);
        btnx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxActionPerformed(evt);
            }
        });

        btnxy.setBackground(new java.awt.Color(102, 102, 102));
        btnxy.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnxy.setText("X^Y");
        btnxy.setBorder(null);
        btnxy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxyActionPerformed(evt);
            }
        });

        btntanh.setBackground(new java.awt.Color(102, 102, 102));
        btntanh.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btntanh.setText("Tanh");
        btntanh.setBorder(null);
        btntanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanhActionPerformed(evt);
            }
        });

        btntan.setBackground(new java.awt.Color(102, 102, 102));
        btntan.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btntan.setText("Tan");
        btntan.setBorder(null);
        btntan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntanActionPerformed(evt);
            }
        });

        btnx2.setBackground(new java.awt.Color(102, 102, 102));
        btnx2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnx2.setText("X^2");
        btnx2.setBorder(null);
        btnx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnx2ActionPerformed(evt);
            }
        });

        btnround.setBackground(new java.awt.Color(102, 102, 102));
        btnround.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnround.setText("=");
        btnround.setActionCommand("");
        btnround.setBorder(null);
        btnround.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnroundActionPerformed(evt);
            }
        });

        btncbr.setBackground(new java.awt.Color(102, 102, 102));
        btncbr.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btncbr.setText("/");
        btncbr.setActionCommand("");
        btncbr.setBorder(null);
        btncbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncbrActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jCheckBoxMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK));
        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("standard");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem1);

        jCheckBoxMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("scientific");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnzero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnone, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntwo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnthree, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnfour, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnfive, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnsix, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnseven, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btneight, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnnine, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnsubtr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnroot, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btncos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btncosh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnxy, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btntan, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btntanh, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnx3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnx2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnbinary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btncbr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnround, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnhex, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(textbox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntanh, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnxy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncbr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnround, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnx2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btneight, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnseven, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnnine, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnsubtr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btncosh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btncos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnsin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnroot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)))
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnfive, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnfour, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnsix, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btntwo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnthree, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btndivide, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbinary, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnhex, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnx3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btndot, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnzero, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add youthisr handling code here:
           this.setResizable(true);
       this.setSize(225, 350);
    }//GEN-LAST:event_formWindowActivated

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.setResizable(true);
       this.setSize(225, 350);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
          this.setResizable(true);
       this.setSize(440,350);
       textbox.setSize(400,30);
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void btnx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnx4ActionPerformed

    private void btnhex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhex1ActionPerformed

    private void btnzero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnzero1ActionPerformed

    private void btnbinary1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinary1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbinary1ActionPerformed

    private void btndot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndot1ActionPerformed

    private void btnplus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnplus1ActionPerformed

    private void btnequal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnequal1ActionPerformed

    private void btnclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclear1ActionPerformed

    private void btnroot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnroot1ActionPerformed

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void btnback1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnback1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnback1ActionPerformed

    private void btnsin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsin1ActionPerformed

    private void textbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox1ActionPerformed

    private void textbox1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textbox1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox1KeyTyped

    private void btnsinh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsinh1ActionPerformed

    private void btneight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneight1ActionPerformed

    private void btnnine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnnine1ActionPerformed

    private void btnlog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlog1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnlog1ActionPerformed

    private void btncos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncos1ActionPerformed

    private void btnmulti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmulti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmulti1ActionPerformed

    private void btncosh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncosh1ActionPerformed

    private void btnseven1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseven1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnseven1ActionPerformed

    private void btnx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnx1ActionPerformed

    private void btnfour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfour1ActionPerformed

    private void btnxy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnxy1ActionPerformed

    private void btnfive1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfive1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfive1ActionPerformed

    private void btntanh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanh1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntanh1ActionPerformed

    private void btnsix1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsix1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsix1ActionPerformed

    private void btntan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntan1ActionPerformed

    private void btnsubtr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubtr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsubtr1ActionPerformed

    private void btnx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnx5ActionPerformed

    private void btnone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnone1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnone1ActionPerformed

    private void btnround1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnround1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnround1ActionPerformed

    private void btntwo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntwo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntwo1ActionPerformed

    private void btncbr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncbr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncbr1ActionPerformed

    private void btnthree1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthree1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnthree1ActionPerformed

    private void btndivide1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivide1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btndivide1ActionPerformed

    private void btnx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx3ActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=(ops * ops * ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnx3ActionPerformed

    private void btnhexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhexActionPerformed
        int a = Integer.parseInt(textbox.getText()); //Hexadecimal.
        textbox.setText(Integer.toString(a,16));
    }//GEN-LAST:event_btnhexActionPerformed

    private void btnbinaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbinaryActionPerformed
        int a = Integer.parseInt(textbox.getText()); //Binary.
        textbox.setText(Integer.toString(a,2));

    }//GEN-LAST:event_btnbinaryActionPerformed

    private void textboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textboxActionPerformed

    private void textboxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textboxKeyTyped
        char c =evt.getKeyChar();
        if(!((c == KeyEvent.VK_DELETE) || Character.isDigit(c)|| (c==KeyEvent.VK_BACK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_textboxKeyTyped

    private void btneightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneightActionPerformed
        // TODO add your handling code here:
        String iNum=textbox.getText()+ btneight.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btneightActionPerformed

    private void btnnineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnineActionPerformed
        // TODO add your handling code here:
        String iNum=textbox.getText()+ btnnine.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnnineActionPerformed

    private void btnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiActionPerformed
        firstnum = Double.parseDouble(textbox.getText());
        textbox.setText("");
        operations=("*");
    }//GEN-LAST:event_btnmultiActionPerformed

    private void btnsevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsevenActionPerformed
        // TODO add your handling code here:

        String iNum=textbox.getText()+ btnseven.getText();
        textbox.setText(iNum);

    }//GEN-LAST:event_btnsevenActionPerformed

    private void btnfourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfourActionPerformed
        // TODO add your handling code here:
        String iNum=textbox.getText()+ btnfour.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnfourActionPerformed

    private void btnfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfiveActionPerformed
        // TODO add your handling code here:

        String iNum=textbox.getText()+ btnfive.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnfiveActionPerformed

    private void btnsixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsixActionPerformed
        // TODO add your handling code here:

        String iNum=textbox.getText()+ btnsix.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnsixActionPerformed

    private void btnsubtrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubtrActionPerformed
        firstnum = Double.parseDouble(textbox.getText());
        textbox.setText("");
        operations=("-");
    }//GEN-LAST:event_btnsubtrActionPerformed

    private void btnoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoneActionPerformed
        // TODO add your handling code here:

        String iNum=textbox.getText()+ btnone.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnoneActionPerformed

    private void btntwoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntwoActionPerformed
        // TODO add your handling code here:

        String iNum=textbox.getText()+ btntwo.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btntwoActionPerformed

    private void btnthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthreeActionPerformed
        // TODO add your handling code here:
        String iNum=textbox.getText()+ btnthree.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnthreeActionPerformed

    private void btndivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivideActionPerformed
        firstnum = Double.parseDouble(textbox.getText());
        textbox.setText("");
        operations=("/");
    }//GEN-LAST:event_btndivideActionPerformed

    private void btnzeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzeroActionPerformed
        // TODO add your handling code here:
        String iNum=textbox.getText()+ btnzero.getText();
        textbox.setText(iNum);
    }//GEN-LAST:event_btnzeroActionPerformed

    private void btndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndotActionPerformed
        if(!textbox.getText().contains("."));

        {
            textbox.setText(textbox.getText() + btndot.getText());
        }
    }//GEN-LAST:event_btndotActionPerformed

    private void btnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnplusActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=ops * (-1);
        textbox. setText(String.valueOf(ops));

    }//GEN-LAST:event_btnplusActionPerformed

    private void btnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnequalActionPerformed

        if (operations == "+")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum + secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }
        if (operations == "*")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum * secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }
        if (operations == "/")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum / secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }
        if (operations == "-")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum - secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }

    }//GEN-LAST:event_btnequalActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        textbox.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrootActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.sqrt(ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnrootActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        firstnum = Double.parseDouble(textbox.getText());
        textbox.setText("");
        operations=("+");
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        String bsp = null;

        if(textbox.getText().length() <= 0) {
        } else {
        }      {
            StringBuilder strB = new StringBuilder(textbox.getText());
            strB.deleteCharAt(textbox.getText().length() - 1);
            bsp = strB.toString();
            textbox.setText(bsp);

        }
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.sin(ops*Math.PI/180);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnsinActionPerformed

    private void btnsinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsinhActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.sinh(ops*Math.PI/180);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnsinhActionPerformed

    private void btnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.log(ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnlogActionPerformed

    private void btncosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncosActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.cos(ops*Math.PI/180);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btncosActionPerformed

    private void btncoshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncoshActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.cosh(ops*Math.PI/180);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btncoshActionPerformed

    private void btnxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxActionPerformed
        double ops ;
        ops= (3.1415926535897932384626433832795);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnxActionPerformed

    private void btnxyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxyActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.pow(ops, ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnxyActionPerformed

    private void btntanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanhActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.tanh(ops*Math.PI/180);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btntanhActionPerformed

    private void btntanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntanActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=Math.tan(ops*Math.PI/180);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btntanActionPerformed

    private void btnx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnx2ActionPerformed
        double ops = Double.parseDouble(String.valueOf(textbox.getText()));
        ops=(ops * ops);
        textbox. setText(String.valueOf(ops));
    }//GEN-LAST:event_btnx2ActionPerformed

    private void btnroundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnroundActionPerformed
        if (operations == "+")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum + secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }
        if (operations == "*")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum * secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }
        if (operations == "/")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum / secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }
        if (operations == "-")
        {
            secondnum = Double.parseDouble(textbox.getText());
            result = firstnum - secondnum;
            answer = answer.valueOf(result);
            textbox.setText(answer);
        }

    }//GEN-LAST:event_btnroundActionPerformed

    private void btncbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncbrActionPerformed
        firstnum = Double.parseDouble(textbox.getText());
        textbox.setText("");
        operations=("/");
    }//GEN-LAST:event_btncbrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scientific_cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scientific_cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnback1;
    private javax.swing.JButton btnbinary;
    private javax.swing.JButton btnbinary1;
    private javax.swing.JButton btncbr;
    private javax.swing.JButton btncbr1;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnclear1;
    private javax.swing.JButton btncos;
    private javax.swing.JButton btncos1;
    private javax.swing.JButton btncosh;
    private javax.swing.JButton btncosh1;
    private javax.swing.JButton btndivide;
    private javax.swing.JButton btndivide1;
    private javax.swing.JButton btndot;
    private javax.swing.JButton btndot1;
    private javax.swing.JButton btneight;
    private javax.swing.JButton btneight1;
    private javax.swing.JButton btnequal;
    private javax.swing.JButton btnequal1;
    private javax.swing.JButton btnfive;
    private javax.swing.JButton btnfive1;
    private javax.swing.JButton btnfour;
    private javax.swing.JButton btnfour1;
    private javax.swing.JButton btnhex;
    private javax.swing.JButton btnhex1;
    private javax.swing.JButton btnlog;
    private javax.swing.JButton btnlog1;
    private javax.swing.JButton btnmulti;
    private javax.swing.JButton btnmulti1;
    private javax.swing.JButton btnnine;
    private javax.swing.JButton btnnine1;
    private javax.swing.JButton btnone;
    private javax.swing.JButton btnone1;
    private javax.swing.JButton btnplus;
    private javax.swing.JButton btnplus1;
    private javax.swing.JButton btnroot;
    private javax.swing.JButton btnroot1;
    private javax.swing.JButton btnround;
    private javax.swing.JButton btnround1;
    private javax.swing.JButton btnseven;
    private javax.swing.JButton btnseven1;
    private javax.swing.JButton btnsin;
    private javax.swing.JButton btnsin1;
    private javax.swing.JButton btnsinh;
    private javax.swing.JButton btnsinh1;
    private javax.swing.JButton btnsix;
    private javax.swing.JButton btnsix1;
    private javax.swing.JButton btnsubtr;
    private javax.swing.JButton btnsubtr1;
    private javax.swing.JButton btntan;
    private javax.swing.JButton btntan1;
    private javax.swing.JButton btntanh;
    private javax.swing.JButton btntanh1;
    private javax.swing.JButton btnthree;
    private javax.swing.JButton btnthree1;
    private javax.swing.JButton btntwo;
    private javax.swing.JButton btntwo1;
    private javax.swing.JButton btnx;
    private javax.swing.JButton btnx1;
    private javax.swing.JButton btnx2;
    private javax.swing.JButton btnx3;
    private javax.swing.JButton btnx4;
    private javax.swing.JButton btnx5;
    private javax.swing.JButton btnxy;
    private javax.swing.JButton btnxy1;
    private javax.swing.JButton btnzero;
    private javax.swing.JButton btnzero1;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField textbox;
    private javax.swing.JTextField textbox1;
    // End of variables declaration//GEN-END:variables
}
